### ISSUE TITLE
The Mako (may) fly...

### ISSUE THREAD

**Issue by Zitchas** [comnom/Eternals#2]
Greetings Comnom. 
I've been working on some ideas for ongoing plot-lines for the remnant, and it occurred to me that your Mako looks like it would fit the concept I have in mind. But for it to be included, at the very least I'm going to need a thumbnail for it (and a 2x thumbnail), although actual blender files would be awesome too.

To make a long story really short, I've been planning on creating a replacement for the gascraft. Or rather, an update: The gascraft is a centuries-old ship, and one that has been mothballed until recently due to the difficulties in using it for research. As part of my Remnant missions, that research is going to get re-invigorated in a variety of ways. As such, it fits that they would eventually start developing a new ship to replace the gascraft.

If you are amenable to that, I think your Mako would fit really well in terms of aesthetics; possible directly as is, or possibly getting Brick to change the colour scheme a little to match the Gull & Pelican. 

I hope to hear from you. I'll monitor this, and I'm on the discord under the same name.

**Comment by comnom** [comment]
The Mako from the [Trin](https://github.com/Elyssaen/trin/tree/development) ? I really don't think that looks anything like a Remnant ship in terms of design, but the license is such that you can use it however you please.

I have all my ES work archived at the moment, as I'm not really interested in doing any work on my plugins or the base game due to the change in development, but Elyssaen stored all the assets here: https://github.com/Elyssaen/trinAssets . Use them how you will.

**Comment by Zitchas** [comment]
Thanks for the response. I was talking with Elyssaen about it too, and he had the same thought. So I might not use it, but the Pelican (gascraft upgrade) will happen one way or another, and since MZ has returned and appointed more devs, stuff's actually getting merged.

Thanks again.
